language: php
php:
  - '7.1.3'
  - '7.2'
  - '7.3'

install:
  - composer update

script:
  - mkdir -p build/logs
  - bin/phpunit tests --coverage-clover build/logs/coverage.xml

after_script:
- bin/php-coveralls -v --coverage_clover build/logs/coverage.xml
